services:
  ocsapplication:
    image: ocsinventory/ocsinventory-docker-image:2.11
    container_name: ocsinventory-server
    restart: always
    ports:
      - "8090:80"
    volumes:
      - "perlcomdata:/etc/ocsinventory-server"
      - "ocsreportsdata:/usr/share/ocsinventory-reports/ocsreports/extensions"
      - "varlibdata:/var/lib/ocsinventory-reports"
      - "httpdconfdata:/etc/apache2/conf-available"
    environment:
      OCS_DB_SERVER: ocsinventory-db
      OCS_DB_PORT: 3306
      OCS_DB_USER: ocsuser
      OCS_DB_PASS: ocspass
      OCS_DB_NAME: ocsweb
      OCS_SSL_ENABLED: 0
    depends_on:
      - ocsdb
    command: /bin/bash -c "apt-get update && apt-get install -y mysql-client && cpan install XML::Entities && /usr/sbin/apache2ctl -D FOREGROUND"

  ocsdb:
    image: mysql:5.7
    container_name: ocsinventory-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: ocsuser
      MYSQL_PASSWORD: ocspass
      MYSQL_DATABASE: ocsweb
    volumes:
      - ./sqldata:/var/lib/mysql
      - ./ocsbase.sql:/docker-entrypoint-initdb.d/ocsbase.sql

volumes:
  perlcomdata:
  ocsreportsdata:
  varlibdata:
  httpdconfdata:
  sqldata:

